# palavras.py

def obter_explicacao(palavra):
    explicacoes = {
        "abacaxi": "O abacaxi é uma fruta grande e tropical. Ele tem uma casca grossa e uma parte interna doce e suculenta. Você pode comer o abacaxi de várias maneiras, como suco ou até mesmo na forma de pedaços.",
        "bola": "A bola é um objeto redondo usado para brincar e praticar esportes como futebol e basquete. Quando você a chuta, ela rola ou pula.",
        "cachorro": "O cachorro é um animal que adora brincar e é o melhor amigo do homem. Ele é leal e gosta de correr atrás de bolas ou passear com seus donos.",
        "gato": "O gato é um animal pequeno e peludo, que gosta de caçar ratos e brincar com objetos. Ele também adora dormir e é muito independente.",
        "casa": "A casa é onde as pessoas moram. Ela pode ter vários cômodos, como sala, cozinha, banheiro e quartos, e serve para nos proteger do tempo e nos dar conforto.",
        "carro": "O carro é um veículo usado para viajar. Ele tem rodas e um motor, e é muito útil para se locomover de um lugar para o outro, como ir ao trabalho ou à escola.",
        "flor": "A flor é a parte colorida das plantas, que geralmente tem um perfume bom. Elas podem ser de várias cores e tamanhos, e atraem abelhas para ajudar na polinização.",
        "árvore": "A árvore é uma planta grande com um tronco e folhas. Ela pode viver por muitos anos e é importante porque ajuda a limpar o ar e dá sombra no verão.",
        "sol": "O sol é uma estrela enorme que fica no centro do nosso sistema solar. Ele nos dá luz e calor, e é responsável por fazer a terra ser quente e habitável.",
        "lua": "A lua é o satélite da Terra. Ela brilha à noite e tem várias fases, como lua cheia, crescente e minguante. Às vezes, a lua parece grande no céu.",
        "estrela": "As estrelas são grandes bolas de fogo que ficam muito longe da Terra. Elas brilham no céu à noite, e algumas são tão grandes que iluminam a escuridão.",
        "pato": "O pato é um animal que vive na água. Ele tem um bico largo e gosta de nadar. Quando sai da água, caminha e voa.",
        "amigo": "Um amigo é uma pessoa com quem você compartilha momentos bons e ruins. Um amigo sempre está ao seu lado para brincar, ajudar e te fazer sorrir.",
        "brinquedo": "Brinquedo é qualquer objeto com o qual as crianças podem brincar, como bonecas, carrinhos ou bolas. Eles são usados para se divertir e explorar a criatividade.",
        "escola": "A escola é um lugar onde as crianças aprendem várias coisas, como matemática, ciências, leitura e história. Também é o lugar onde você faz amigos.",
        "floresta": "A floresta é um grande espaço cheio de árvores, plantas e animais. Muitas vezes, ela tem um ambiente fresco e pode ser encontrada em locais como a Amazônia.",
        "livro": "O livro é um objeto que contém histórias, informações e imagens. Você pode ler para aprender novas coisas ou se divertir com histórias de aventura.",
        "água": "A água é um líquido muito importante para a vida. Nós bebemos água todos os dias, e ela também serve para as plantas e os animais viverem.",
        "comida": "Comida é o que você come para ficar saudável e com energia. Pode ser arroz, feijão, frutas ou até um doce como chocolate.",
        "amarelo": "Amarelo é uma cor que lembra o sol e o ouro. É uma cor brilhante e alegre que pode ser encontrada em flores e outros objetos.",
        "verde": "Verde é a cor das folhas das árvores e das plantas. É uma cor tranquila e ligada à natureza, simbolizando frescor e vida.",
        "azul": "Azul é a cor do céu e do mar. É uma cor fria e relaxante, que transmite paz e calma.",
        "vermelho": "Vermelho é uma cor muito forte e vibrante. Pode ser vista em coisas como maçãs, corações e até o fogo.",
        "preto": "Preto é uma cor escura que é o oposto do branco. Quando a luz não consegue passar, o que vemos é a cor preta.",
        "branco": "Branco é a cor da neve e da nuvem. É uma cor clara que pode simbolizar pureza, calma e simplicidade.",
        "feliz": "Feliz é quando você se sente bem, animado e sorrindo. Pode acontecer quando você recebe um presente ou brinca com seus amigos.",
        "triste": "Triste é quando você se sente para baixo e não está tão animado. Às vezes, isso acontece quando algo não sai como você queria.",
        "calor": "Calor é o que sentimos quando a temperatura está alta, como no verão. Ele vem do sol e faz as coisas ficarem quentes.",
        "frio": "Frio é quando a temperatura está baixa. Você sente frio quando está em um lugar gelado ou no inverno.",
        "voar": "Voar é quando os animais, como pássaros ou aviões, sobem no ar e se movem. Você pode ver pássaros voando no céu ou aviões cruzando as nuvens.",
        "correr": "Correr é quando você anda muito rápido, normalmente para brincar ou chegar a algum lugar. Algumas pessoas correm para se exercitar.",
        "nadar": "Nadar é quando você se move na água, como um peixe ou um pato. Nadar é uma atividade muito divertida e boa para o corpo.",
        "dançar": "Dançar é mover seu corpo ao ritmo de uma música. Você pode dançar para se divertir ou em uma festa.",
        "pular": "Pular é quando você sobe no ar e cai de novo, usando as pernas. As crianças adoram pular, seja com uma corda ou saltando por diversão.",
        "abraço": "O abraço é quando você envolve outra pessoa com seus braços, mostrando carinho e afeto. Abraçar é uma forma de mostrar que você se importa.",
        "beijo": "O beijo é quando você toca a outra pessoa com seus lábios, normalmente para mostrar amor, carinho ou amizade.",
        "caminhar": "Caminhar é quando você anda devagar, sem correr. Você caminha para ir a lugares, como à escola ou ao parquinho.",
        "jogar": "Jogar é quando você participa de um jogo. Pode ser jogar bola, brincar de esconde-esconde ou até videogame.",
        "subir": "Subir é quando você vai para cima, como subir uma escada ou subir em uma árvore para pegar um fruto.",
        "descer": "Descer é o oposto de subir. Quando você desce, vai para baixo, como descer uma ladeira ou uma escada.",
        "roda": "A roda é uma peça redonda que ajuda objetos a se moverem, como um carro ou uma bicicleta. As rodas giram e fazem com que tudo se mova.",
        "porta": "A porta é uma abertura nas paredes da casa ou de outros lugares, que serve para entrar e sair de um lugar.",
        "janela": "A janela é uma abertura nas paredes da casa, geralmente com vidro, que serve para você ver o lado de fora.",
        "chuva": "A chuva é quando a água cai do céu. Às vezes, a chuva é leve, e outras vezes é forte, mas ela ajuda as plantas a crescerem.",
        "neve": "A neve é água congelada que cai do céu em flocos. Ela cobre o chão, deixando tudo branquíssimo e é muito comum em lugares frios.",
        "vento": "O vento é o ar em movimento. Quando você sente o vento no rosto, é porque ele está se movendo rapidamente.",
        "sol": "O sol é uma estrela que ilumina o nosso planeta e nos dá calor. Sem o sol, a vida na Terra não seria possível.",
        "lua": "A lua é um grande satélite que fica girando ao redor da Terra. Ela brilha à noite e pode ser vista de várias formas, como cheia ou crescente.",
        "coração": "O coração é o órgão que bombeia o sangue pelo corpo. Também é um símbolo de amor e carinho."
    }
    
    return explicacoes.get(palavra.lower(), None)  # Retorna a explicação ou None se não encontrar a palavra

